/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A.View;

import B.Controller.CadastrarAlunoController;
import B.Controller.ListarAlunoController;
import C.Model.Aluno;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo
 */
public class PrimeiraEntrega extends javax.swing.JFrame
{
    private DefaultTableModel tab;
            
    /**
     * Creates new form ListarAlunoView
     */
    public PrimeiraEntrega()
    {       
        initComponents();
        this.tab = (DefaultTableModel) jTableAlunos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButtonListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlunos = new javax.swing.JTable();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabelMae = new javax.swing.JLabel();
        jLabelPai = new javax.swing.JLabel();
        jLabelCodMunicipal = new javax.swing.JLabel();
        jTextFieldNomeAluno = new javax.swing.JTextField();
        jTextFieldMae = new javax.swing.JTextField();
        jTextFieldCodMunicipal = new javax.swing.JTextField();
        jTextFieldPai = new javax.swing.JTextField();
        jButtonSalvarAlterecoes = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonLimparTab = new javax.swing.JButton();
        jLabelArquivo = new javax.swing.JLabel();
        jTextFieldArquivo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonListarActionPerformed(evt);
            }
        });

        jTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Cód. Municipal", "Aluno", "Mãe", "Pai"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTableAlunos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jTableAlunosMouseReleased(evt);
            }
        });
        jTableAlunos.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTableAlunosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlunos);

        jButtonAtualizar.setText("Editar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome");

        jLabelMae.setText("Mãe ");

        jLabelPai.setText("Pai");

        jLabelCodMunicipal.setText("Cód. Municipal");

        jTextFieldNomeAluno.setText("nome do aluno");

        jTextFieldMae.setText("nome da mãe");
        jTextFieldMae.setToolTipText("");

        jTextFieldCodMunicipal.setText("Código Municipal");

        jTextFieldPai.setText("nome do pai");

        jButtonSalvarAlterecoes.setText("Salvar Alterações");
        jButtonSalvarAlterecoes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSalvarAlterecoesActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonLimparTab.setText("Limpar Tabela");
        jButtonLimparTab.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLimparTabActionPerformed(evt);
            }
        });

        jLabelArquivo.setText("Arquivo");

        jTextFieldArquivo.setText("/home/paulo/Desktop/arquivo.bin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelMae)
                            .addComponent(jLabelPai))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomeAluno)
                            .addComponent(jTextFieldMae)
                            .addComponent(jTextFieldPai)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCodMunicipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodMunicipal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButtonListar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimparTab)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonSalvarAlterecoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldArquivo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodMunicipal)
                    .addComponent(jTextFieldCodMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelPai))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMae))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonListar)
                        .addComponent(jButtonCadastrar)
                        .addComponent(jButtonAtualizar)
                        .addComponent(jButtonExcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSalvarAlterecoes)
                        .addComponent(jButtonLimparTab)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArquivo)
                    .addComponent(jTextFieldArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonListarActionPerformed
    {//GEN-HEADEREND:event_jButtonListarActionPerformed
        Aluno aluno = new Aluno();
        File arquivo = new File(jTextFieldArquivo.getText());
        ListarAlunoController alunoController = new ListarAlunoController();
        List<Aluno> alunos = alunoController.listar(arquivo);

        for(Aluno a : alunos)
        {
            tab.addRow(new String[] {
                a.getCodMunicipal(),
                a.getNome(),
                a.getMae(),
                a.getPai()});               
        }
        tab.fireTableDataChanged();
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonExcluirActionPerformed
    {//GEN-HEADEREND:event_jButtonExcluirActionPerformed
        int linhaSelecionada = jTableAlunos.getSelectedRow();
        if(linhaSelecionada != -1)
        {
            tab.removeRow(linhaSelecionada);
            tab.fireTableDataChanged();
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAtualizarActionPerformed
    {//GEN-HEADEREND:event_jButtonAtualizarActionPerformed
        
        int linhaSelecionada = jTableAlunos.getSelectedRow();
        if(linhaSelecionada != -1)
        {
            tab.setValueAt(jTextFieldCodMunicipal.getText(), linhaSelecionada, 0);
            tab.setValueAt(jTextFieldNomeAluno.getText(), linhaSelecionada, 1);
            tab.setValueAt(jTextFieldMae.getText(), linhaSelecionada, 2);
            tab.setValueAt(jTextFieldPai.getText(), linhaSelecionada, 3);
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jTableAlunosKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTableAlunosKeyReleased
    {//GEN-HEADEREND:event_jTableAlunosKeyReleased
        int linhaSelecionada = jTableAlunos.getSelectedRow();
        if(linhaSelecionada != -1)
        {
            jTextFieldCodMunicipal.setText((String) jTableAlunos.getValueAt(linhaSelecionada, 0));
            jTextFieldNomeAluno.setText((String) jTableAlunos.getValueAt(linhaSelecionada, 1));
            jTextFieldMae.setText((String) jTableAlunos.getValueAt(linhaSelecionada, 2));
            jTextFieldPai.setText((String) jTableAlunos.getValueAt(linhaSelecionada, 3));
        }
    }//GEN-LAST:event_jTableAlunosKeyReleased

    private void jTableAlunosMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableAlunosMouseReleased
    {//GEN-HEADEREND:event_jTableAlunosMouseReleased
        int linhaSelecionada = jTableAlunos.getSelectedRow();
        if(linhaSelecionada != -1)
        {
            jTextFieldCodMunicipal.setText((String) jTableAlunos.getValueAt(linhaSelecionada, 0));
            jTextFieldNomeAluno.setText((String) jTableAlunos.getValueAt(linhaSelecionada, 1));
            jTextFieldMae.setText((String) jTableAlunos.getValueAt(linhaSelecionada, 2));
            jTextFieldPai.setText((String) jTableAlunos.getValueAt(linhaSelecionada, 3));
        }
    }//GEN-LAST:event_jTableAlunosMouseReleased

    private void jButtonSalvarAlterecoesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSalvarAlterecoesActionPerformed
    {//GEN-HEADEREND:event_jButtonSalvarAlterecoesActionPerformed
        File arquivo = new File(jTextFieldArquivo.getText());
        List<Aluno> alunos = new ArrayList<Aluno>();
        tab.fireTableDataChanged();
        
        for(int linha = 0; linha < tab.getRowCount(); linha++)
        {
            Aluno a = new Aluno();
            a.setCodMunicipal(tab.getValueAt(linha, 0).toString());
            a.setNome(tab.getValueAt(linha, 1).toString());
            a.setMae(tab.getValueAt(linha, 2).toString());
            a.setPai(tab.getValueAt(linha, 3).toString());
            alunos.add(a);           
        }
        CadastrarAlunoController controller = new CadastrarAlunoController();
        controller.cadastrar(arquivo, alunos);
    }//GEN-LAST:event_jButtonSalvarAlterecoesActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCadastrarActionPerformed
    {//GEN-HEADEREND:event_jButtonCadastrarActionPerformed
        Object[] row = new Object[4];
        row[0] = jTextFieldCodMunicipal.getText();
        row[1] = jTextFieldNomeAluno.getText();
        row[2] = jTextFieldMae.getText();
        row[3] = jTextFieldPai.getText();
        tab.addRow(row);
        tab.fireTableDataChanged();
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonLimparTabActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLimparTabActionPerformed
    {//GEN-HEADEREND:event_jButtonLimparTabActionPerformed
        tab.fireTableDataChanged();
        for(int i = 0; i < tab.getRowCount(); i++)
        {
            tab.removeRow(i);
        }
        tab.fireTableDataChanged();
    }//GEN-LAST:event_jButtonLimparTabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PrimeiraEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PrimeiraEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PrimeiraEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PrimeiraEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PrimeiraEntrega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimparTab;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonSalvarAlterecoes;
    private javax.swing.JLabel jLabelArquivo;
    private javax.swing.JLabel jLabelCodMunicipal;
    private javax.swing.JLabel jLabelMae;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlunos;
    private javax.swing.JTextField jTextFieldArquivo;
    private javax.swing.JTextField jTextFieldCodMunicipal;
    private javax.swing.JTextField jTextFieldMae;
    private javax.swing.JTextField jTextFieldNomeAluno;
    private javax.swing.JTextField jTextFieldPai;
    // End of variables declaration//GEN-END:variables
}
